stages:
  download:
    cmd: python ds360/src/download_iris.py
    outs:
      - ds360/data/raw_data/iris.csv

  preprocess:
    cmd: python ds360/src/data_processing.py
    deps:
      - ds360/data/raw_data/iris.csv
      - ds360/src/data_processing.py
    outs:
      - ds360/data/preprocessed_data/iris_clean.csv

  train_model:
    cmd: python ds360/src/modelling.py
    deps:
      - ds360/data/preprocessed_data/iris_clean.csv
      - ds360/src/modelling.py
    outs:
      - ds360/models/random_forest_iris_model.pkl
      - ds360/models/metrics.json
      - ds360/models/features.json
